version: '2'
services:
  web:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    container_name: web
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
      - 3035:3035
    stdin_open: true
    tty: true
    volumes:
      - .:/my_app
      - /my_app/node_modules
    volumes_from:
      - datastore
  db:
    image: mysql
    volumes_from:
      - datastore
  datastore:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
      - /data
      - /my_app/tmp/sockets