default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  #rootpassword: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default